### ISSUE TITLE
Use a builder pattern to create MonteCarlo structs

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#82]
When I first read through [the code of the MonteCarlo propagator](https://github.com/lumol-org/lumol/blob/master/src/core/src/sim/mc/monte_carlo.rs#L154-L162) I got really confused because it makes no sense to sample a move whose frequency is smaller than the sampled float. Makes a lot more sense if they are cumulative frequencies. It turns out they are, but the attribute is named `frequencies`.

Hovewer, if we renamed the attribute to reflect that they are cumulative frequencies things get weird because in the beginning (before `setup` is called) they are frequencies. 
It turns out the weirdness comes from the methods `add` and `add_move_with_acceptance`, since they are the ones dealing with frequencies before the `setup`. 

All of this to ask: is there sometimes a situation where we need to initialize a `MonteCarlo` propagator without the associated moves and add the moves later ? Because if not one could pass a `Vec` of `(Box<MCMove>, f64, Option<f64>)` to the constructor. This way `frequencies` would always be cumulative frequencies, and more importantly we would not have methods that can panic, which is always good.

**Comment by g-bauer** [comment]
I totally agree that the whole `frequencies` in the `MonteCarlo` code are confusing (there is also the frequency to update amplitudes for moves - maybe we should change it to `update_interval`).

> All of this to ask: is there sometimes a situation where we need to initialize a MonteCarlo propagator without the associated moves and add the moves later ? Because if not one could pass a Vec of (Box<MCMove>, f64, Option<f64>) to the constructor. 

I can't think of such a situation. However, I feel that - when using lumol as a lib - it is more convenient to add moves [separately](https://github.com/g-bauer/lumol/blob/dbb5cce687cc2d7e72c311cf8e1a0053f8105b77/examples/mc_npt_ethane.rs#L74-L79). 

But I agree on the point that this is not very transparent and we should make it more plausible. That being said, I am working on the user manual part of the MC stuff. Since it already includes `resize` moves (which are currently in PR) I want to wait till we merge. We maybe should also add more information to the API documentation of `MonteCarlo`.

**Comment by Luthaf** [comment]
We can also use the builder pattern here, and have a `MonteCarloBuilder/MonteCarloOptions` struct where one can add moves one by one, and then call `MonteCarloBuilder::build(self) -> MonteCarlo` to normalize the move probabilities and setup the update intervals.
