### ISSUE TITLE
Crashing examples

### ISSUE THREAD

**Issue by antoinewdg** [lumol-org/lumol#89]
In addition to what I mentioned in #88, the `minimization` example panics:
```
thread 'main' panicked at 'Potential energy is infinite!', /home/antoinewdg/Development/lumol/src/core/src/sys/compute.rs:119
```

I also get warnings on `mc_npt_spce` and `mc_npt_ethane`, is this intentional ?
```
Warning: No potential defined for the pair (H, O) (from /home/antoinewdg/Development/lumol/src/core/src/sys/interactions.rs:181)
Warning: No potential defined for the pair (H, H) (from /home/antoinewdg/Development/lumol/src/core/src/sys/interactions.rs:181)
Initial energy: -76663.13161568451
```
```
Warning: Tried to increase the maximum amplitude for translations to more than the set maximum. (from /home/antoinewdg/Development/lumol/src/core/src/sim/mc/moves/translate.rs:140)
Warning: Tried to increase the maximum amplitude for rotations to more than 180°. (from /home/antoinewdg/Development/lumol/src/core/src/sim/mc/moves/rotate.rs:125)
```

**Comment by g-bauer** [comment]
> I also get warnings on mc_npt_spce and mc_npt_ethane, is this intentional ?

We can get rid of the missing potential functions by adding `NullPotential`s, but the simulation is doing the same in both cases. What I find a bit inconvenient is that one has to define both (H, O) as well as (O, H).  

The warnings for the amplitudes are working as intended. This warning tells the user that the targeted acceptance for the move (if specified) may not be reached since it makes no sense to inrease the amplitude for the displacements.

**Comment by Luthaf** [comment]
> In addition to what I mentioned in #88, the minimization example panics:

Got this one! This is due to the tail correction code, and specifically here: https://github.com/lumol-org/lumol/blob/411707a7171bde4477b56ab90db8618427529906/src/core/src/sys/energy.rs#L65; where we are dividing by the volume even in the case of infinite unit cell (where the volume is zero ...).

> What I find a bit inconvenient is that one has to define both (H, O) as well as (O, H).

We should not have to, all pairs should be normalized such as specifying and querying for (H, O) or (O, H) gives the same value.

Do you have an example of misbehaving code here?

**Comment by g-bauer** [comment]
Sorry, I got that wrong. I added a bonding potential but no pair interaction for the same pair. That got me confused.
